server:
  port : 8090
spring:
  config:
    import: classpath:/config/database.yaml
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      leak-detection-threshold: 5000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 50MB
      max-file-size: 20MB
logging:
  level:
    root: debug
  interceptor:
    enabled: false
storage:
  book_files_path: "E:\\Projects\\Storage\\lesson37_bookstore_storage\\files\\"
springdoc:
  swagger-ui:
    path: /docs.html
  api-docs:
    path: /api/docs.yaml

---

spring:
  config:
    activate:
      on-profile: db_debug
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    hibernate:
      SQL: debug
    type:
      descriptor:
        sql:
          BasicBinder: trace