server:
  port : 8090
spring:
  config:
    import: classpath:/config/database.yaml
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
        sql:
          BasicBinder: TRACE
  interceptor:
    enabled: false